//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivePeriodRecord
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public int RecordType { get; set; }
        public Nullable<int> StageOne { get; set; }
        public Nullable<int> StageTwo { get; set; }
        public Nullable<int> StageThree { get; set; }
        public decimal PVSurplus { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Remarks { get; set; }
        public string OrderNumber { get; set; }
    
        public virtual User User { get; set; }
    }
}
