//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.ActivityDiscountOneInfo = new HashSet<ActivityDiscountOneInfo>();
            this.ActivityDiscountTwo = new HashSet<ActivityDiscountTwo>();
            this.ActivityGiftsPurchased = new HashSet<ActivityGiftsPurchased>();
            this.ActivityProduct = new HashSet<ActivityProduct>();
            this.ActivityOrderType = new HashSet<ActivityOrderType>();
            this.ActivityUser = new HashSet<ActivityUser>();
            this.ActivityGifts = new HashSet<ActivityGifts>();
            this.ActivityUserType = new HashSet<ActivityUserType>();
            this.ActivityProductPurchased = new HashSet<ActivityProductPurchased>();
            this.ActivityGiftsPrice = new HashSet<ActivityGiftsPrice>();
        }
    
        public System.Guid ID { get; set; }
        public string ActivityName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int ActivityObjectForm { get; set; }
        public int ActivityForm { get; set; }
        public string ActivityExplain { get; set; }
        public Nullable<decimal> BasicsMoney { get; set; }
        public Nullable<decimal> DiscountMoney { get; set; }
        public bool IfAll { get; set; }
        public bool IfEnable { get; set; }
        public Nullable<int> BuyNumber { get; set; }
        public Nullable<bool> IfDoubleGive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityDiscountOneInfo> ActivityDiscountOneInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityDiscountTwo> ActivityDiscountTwo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityGiftsPurchased> ActivityGiftsPurchased { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityProduct> ActivityProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityOrderType> ActivityOrderType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityUser> ActivityUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityGifts> ActivityGifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityUserType> ActivityUserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityProductPurchased> ActivityProductPurchased { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityGiftsPrice> ActivityGiftsPrice { get; set; }
    }
}
