//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUserOperationLog
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> AdminUserID { get; set; }
        public string AdminUserCode { get; set; }
        public string OrderNumber { get; set; }
        public string OrderTypeName { get; set; }
        public string UserCode { get; set; }
        public Nullable<decimal> MoneyProduct { get; set; }
        public Nullable<decimal> MoneyTransport { get; set; }
        public Nullable<decimal> OrderMoney { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string OldLevel { get; set; }
        public string NewLevel { get; set; }
        public Nullable<int> OperationType { get; set; }
        public string PCDealerCode { get; set; }
        public string PPDealerCode { get; set; }
        public string DeptName { get; set; }
        public string UserName { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
    }
}
