//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BwslRetailEntities : DbContext
    {
        public BwslRetailEntities()
            : base("name=BwslRetailEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivePeriodRecord> ActivePeriodRecord { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityDiscountOneInfo> ActivityDiscountOneInfo { get; set; }
        public virtual DbSet<ActivityDiscountTwo> ActivityDiscountTwo { get; set; }
        public virtual DbSet<ActivityGifts> ActivityGifts { get; set; }
        public virtual DbSet<ActivityGiftsPurchased> ActivityGiftsPurchased { get; set; }
        public virtual DbSet<ActivityOrderType> ActivityOrderType { get; set; }
        public virtual DbSet<ActivityProduct> ActivityProduct { get; set; }
        public virtual DbSet<ActivityProductPurchased> ActivityProductPurchased { get; set; }
        public virtual DbSet<ActivityUser> ActivityUser { get; set; }
        public virtual DbSet<ActivityUserType> ActivityUserType { get; set; }
        public virtual DbSet<AdminMenu> AdminMenu { get; set; }
        public virtual DbSet<AdminRole> AdminRole { get; set; }
        public virtual DbSet<AdminUser> AdminUser { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Balance> Balance { get; set; }
        public virtual DbSet<BrowseRecordsUrl> BrowseRecordsUrl { get; set; }
        public virtual DbSet<DealerPlaceRelation> DealerPlaceRelation { get; set; }
        public virtual DbSet<DeLevel> DeLevel { get; set; }
        public virtual DbSet<DiscountTwoInfo> DiscountTwoInfo { get; set; }
        public virtual DbSet<ExceptionRecord> ExceptionRecord { get; set; }
        public virtual DbSet<ExChange> ExChange { get; set; }
        public virtual DbSet<FreightRules> FreightRules { get; set; }
        public virtual DbSet<GiftProduct> GiftProduct { get; set; }
        public virtual DbSet<HonLevel> HonLevel { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<MessageType> MessageType { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderConfig> OrderConfig { get; set; }
        public virtual DbSet<OrderProduct> OrderProduct { get; set; }
        public virtual DbSet<OrderType> OrderType { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductAttribute> ProductAttribute { get; set; }
        public virtual DbSet<ProductCollection> ProductCollection { get; set; }
        public virtual DbSet<ProductComment> ProductComment { get; set; }
        public virtual DbSet<ProductImage> ProductImage { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<RecordPrizeInfo> RecordPrizeInfo { get; set; }
        public virtual DbSet<RoleMenu> RoleMenu { get; set; }
        public virtual DbSet<ServerPrizeInfo> ServerPrizeInfo { get; set; }
        public virtual DbSet<ServiceCenter> ServiceCenter { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
        public virtual DbSet<TeachPrizeInfo> TeachPrizeInfo { get; set; }
        public virtual DbSet<TimesSpendPrizeInfo> TimesSpendPrizeInfo { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserAddress> UserAddress { get; set; }
        public virtual DbSet<UserCoupons> UserCoupons { get; set; }
        public virtual DbSet<UserPwdCode> UserPwdCode { get; set; }
        public virtual DbSet<WeekPrize> WeekPrize { get; set; }
        public virtual DbSet<ZkJDPrizeInfo> ZkJDPrizeInfo { get; set; }
        public virtual DbSet<Dealer_Be_Balance_Bak> Dealer_Be_Balance_Bak { get; set; }
        public virtual DbSet<ActivityGiftsPrice> ActivityGiftsPrice { get; set; }
        public virtual DbSet<AdminMenuAction> AdminMenuAction { get; set; }
        public virtual DbSet<ProductStockHistory> ProductStockHistory { get; set; }
        public virtual DbSet<RoleMenuAction> RoleMenuAction { get; set; }
        public virtual DbSet<AdminUserOperationLog> AdminUserOperationLog { get; set; }
        public virtual DbSet<IndexImagesManage> IndexImagesManage { get; set; }
        public virtual DbSet<ImgDeLevel> ImgDeLevel { get; set; }
        public virtual DbSet<Notice> Notice { get; set; }
        public virtual DbSet<NoticeType> NoticeType { get; set; }
    }
}
