//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.EntityClient;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;

    public partial class BwslRetailRelationEntities : DbContext
    {
        public BwslRetailRelationEntities()
            : base("name=BwslRetailRelationEntities")
        {
        }
        public BwslRetailRelationEntities(string connectionString)
                      : base(connectionString)
        {
        }
        public static string GetConnection()
        {
            string DataSource = "103.15.105.85,64757";//  103.15.105.85,64757

            string DataBase = "BwslRetailRelation"; // 

            string UserId = "SQLuserFL";//     SQLuserFL

            string PassWord = "hqG@5G8K42ahNsq";// hqG@5G8K42ahNsq


            SqlConnectionStringBuilder sqlBuilder = new SqlConnectionStringBuilder();

            sqlBuilder.DataSource = DataSource;

            sqlBuilder.InitialCatalog = DataBase;

            sqlBuilder.PersistSecurityInfo = true;

            //sqlBuilder.IntegratedSecurity = true;

            sqlBuilder.MultipleActiveResultSets = true;

            sqlBuilder.UserID = UserId;

            sqlBuilder.Password = PassWord;

            EntityConnectionStringBuilder entityBuilder = new EntityConnectionStringBuilder();

            entityBuilder.ProviderConnectionString = sqlBuilder.ToString();

            entityBuilder.Metadata = "res://*/CM.BwslRetailRelationModel.csdl|res://*/CM.BwslRetailRelationModel.ssdl|res://*/CM.BwslRetailRelationModel.msl";
            //res://*/CM.BwslRetailRelationModel.csdl|res://*/CM.BwslRetailRelationModel.ssdl|res://*/CM.BwslRetailRelationModel.msl
            entityBuilder.Provider = "System.Data.SqlClient";

            string tt = entityBuilder.ToString();

            return tt;

        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Balance> Balance { get; set; }
        public virtual DbSet<DealerPlaceRelation> DealerPlaceRelation { get; set; }
        public virtual DbSet<DealerRecomRelation> DealerRecomRelation { get; set; }
        public virtual DbSet<PlaceRelation> PlaceRelation { get; set; }
        public virtual DbSet<RecomRelation> RecomRelation { get; set; }
        public virtual DbSet<RecordPrizeInfo> RecordPrizeInfo { get; set; }
        public virtual DbSet<ServerPrizeInfo> ServerPrizeInfo { get; set; }
        public virtual DbSet<TeachPrizeInfo> TeachPrizeInfo { get; set; }
        public virtual DbSet<TimesSpendPrizeInfo> TimesSpendPrizeInfo { get; set; }
        public virtual DbSet<WeekPrize> WeekPrize { get; set; }
        public virtual DbSet<WeekPrize_UnActiveDealer> WeekPrize_UnActiveDealer { get; set; }
        public virtual DbSet<ZkJDPrizeInfo> ZkJDPrizeInfo { get; set; }
        public virtual DbSet<Dealer_Be_Balance_Bak> Dealer_Be_Balance_Bak { get; set; }
        public virtual DbSet<Grant_BusiData_ErrorResult> Grant_BusiData_ErrorResult { get; set; }
        public virtual DbSet<Grant_BusiData_ErrRecord> Grant_BusiData_ErrRecord { get; set; }
        public virtual DbSet<SaleCustomerPrizeInfo> SaleCustomerPrizeInfo { get; set; }
        public virtual DbSet<SalePrizeInfo> SalePrizeInfo { get; set; }
        public virtual DbSet<Syn_BusiData_ErrorResult> Syn_BusiData_ErrorResult { get; set; }
        public virtual DbSet<Syn_BusiData_ErrRecord> Syn_BusiData_ErrRecord { get; set; }
        public virtual DbSet<WeekPrize_NumberThreeBak> WeekPrize_NumberThreeBak { get; set; }
        public virtual DbSet<WeekPrize_UnActiveDealer_BalanceNumberThreeBak> WeekPrize_UnActiveDealer_BalanceNumberThreeBak { get; set; }
    }
}
