//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer_Be_Balance_Bak
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int TPoint_Point { get; set; }
        public int RPoint_Point { get; set; }
        public int AStage_StageCount { get; set; }
        public bool State_LoginState { get; set; }
        public bool State_MoneyOPState { get; set; }
        public bool State_AccountState { get; set; }
        public decimal EleMoney_Money { get; set; }
        public decimal BonusMoney_Money { get; set; }
        public string HonLevelId { get; set; }
        public string DeLevelId { get; set; }
        public decimal ReduceMoney_Money { get; set; }
        public Nullable<System.DateTime> BusiDate { get; set; }
        public Nullable<decimal> AreaTotalPoint_A { get; set; }
        public Nullable<decimal> AreaTotalPoint_B { get; set; }
        public Nullable<decimal> AreaRPoint_A { get; set; }
        public Nullable<decimal> AreaRPoint_B { get; set; }
    }
}
