//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionRecord
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string OrderType { get; set; }
        public Nullable<decimal> OrderMoney { get; set; }
        public Nullable<int> OrderPV { get; set; }
        public string CZdealer { get; set; }
        public string Kkdealer { get; set; }
        public string SSdealer { get; set; }
        public string CKdealer { get; set; }
        public string SKdealer { get; set; }
        public Nullable<decimal> ZZMoney { get; set; }
        public string ZZRemarks { get; set; }
    }
}
