//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExChange
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public int MoneyType { get; set; }
        public int ZMoneyType { get; set; }
        public decimal BeforeChangeMoney { get; set; }
        public decimal ChangeMoney { get; set; }
        public decimal AfterChangeMoney { get; set; }
        public System.DateTime ChangeTime { get; set; }
        public string ChangeMarks { get; set; }
        public string OrderNum { get; set; }
        public string IsBak { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<decimal> FeeRat { get; set; }
        public Nullable<decimal> FeeAmount { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public Nullable<int> ExChangeType { get; set; }
    
        public virtual User User { get; set; }
    }
}
