//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public System.Guid ID { get; set; }
        public System.Guid MessageTypeID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.Guid> AdminID { get; set; }
        public string MessageContent { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string ReplyContent { get; set; }
        public int DataType { get; set; }
        public int MsgLevel { get; set; }
        public Nullable<System.Guid> PID { get; set; }
        public string Title { get; set; }
        public Nullable<int> MessageState { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
        public virtual MessageType MessageType { get; set; }
        public virtual User User { get; set; }
    }
}
