//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> NoticeTypeID { get; set; }
        public Nullable<System.Guid> AdminUserID { get; set; }
        public string Title { get; set; }
        public string Descn { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> ReadQuantity { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> State { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
        public virtual NoticeType NoticeType { get; set; }
    }
}
