//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public System.Guid ID { get; set; }
        public System.Guid OrderID { get; set; }
        public System.Guid ProductID { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<int> ProductNum { get; set; }
        public string IsBak { get; set; }
        public Nullable<int> ShoppingProductType { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
