//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderConfig
    {
        public System.Guid ID { get; set; }
        public System.Guid ProductID { get; set; }
        public int OrderTypeID { get; set; }
        public decimal Price { get; set; }
        public decimal PV { get; set; }
        public string LevelList { get; set; }
        public bool IsRequired { get; set; }
        public Nullable<decimal> PriceMin { get; set; }
        public Nullable<bool> IfCount { get; set; }
        public string OldLevelList { get; set; }
        public Nullable<System.DateTime> STime1 { get; set; }
        public Nullable<System.DateTime> ETime1 { get; set; }
    
        public virtual OrderType OrderType { get; set; }
        public virtual Product Product { get; set; }
    }
}
