//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceRelation
    {
        public System.Guid ID { get; set; }
        public Nullable<int> Layer { get; set; }
        public Nullable<System.Guid> DealerId { get; set; }
        public Nullable<System.Guid> PDealerId { get; set; }
        public string AreaName { get; set; }
    }
}
