//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerPrizeInfo
    {
        public string Id { get; set; }
        public int BalanceNumber { get; set; }
        public string DealerId { get; set; }
        public string SubDealerId { get; set; }
        public string OrderId { get; set; }
        public int TotalPV { get; set; }
        public decimal Percentum { get; set; }
        public string SCType { get; set; }
    }
}
