//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceCenter()
        {
            this.Order = new HashSet<Order>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string ServiceCenterName { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<int> AuditResult { get; set; }
        public Nullable<int> SCType { get; set; }
        public string CManager { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> CountyId { get; set; }
        public string Consignee { get; set; }
        public string ReceivingCall { get; set; }
        public string ReceivingAddress { get; set; }
        public string ZipCode { get; set; }
        public string OldName { get; set; }
        public string OldID { get; set; }
        public Nullable<bool> IFOrder { get; set; }
        public Nullable<int> IsHealthCheckRight { get; set; }
        public string ParentDealerCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual User User { get; set; }
    }
}
