//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Syn_BusiData_ErrorResult
    {
        public string Id { get; set; }
        public int BalanceNumber { get; set; }
        public System.DateTime BusiDate { get; set; }
        public Nullable<int> ErrTag { get; set; }
        public string Discription { get; set; }
    }
}
