//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMK.Model.CM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekPrize_NumberThreeBak
    {
        public string Id { get; set; }
        public int BalanceNumber { get; set; }
        public string DealerId { get; set; }
        public decimal RecomPrize { get; set; }
        public decimal SalePrize { get; set; }
        public decimal TeachPrize { get; set; }
        public decimal RecordPrize { get; set; }
        public decimal VipPrize { get; set; }
        public decimal ServicePrize { get; set; }
        public decimal ServiceSurplus { get; set; }
        public decimal RecomServiceFirst { get; set; }
        public decimal RecomServiceSecond { get; set; }
        public decimal ReduceSale { get; set; }
        public decimal ReduceService { get; set; }
        public decimal ReduceIT { get; set; }
        public decimal TotalPrize { get; set; }
        public bool IsGrant { get; set; }
        public Nullable<System.DateTime> GrantDate { get; set; }
        public string GrantMarks { get; set; }
        public string DealerDeLevel { get; set; }
        public string DealerHonLevel { get; set; }
        public string DealerCode { get; set; }
        public Nullable<decimal> HonPrize { get; set; }
        public Nullable<System.DateTime> BalanceDate { get; set; }
        public Nullable<decimal> TimesSpendPrize { get; set; }
    }
}
